language: bash
sudo: required

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install screenresolution; fi

script:
    - time ./fetchfusion --travis -v
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then shellcheck -e SC2244 -e SC2243 fetchfusion; fi
    # Check for lines longer than 100 chars.
    - if grep '.\{102\}' fetchfusion; then (exit 1); else (exit 0); fi
